---
- name: this is the play for adding an ssh key to a gateone user
  hosts: atmosphere
  vars:
    EXTERNAL_HOST_KEY_DIR: "/var/lib/gateone/users/{{ ATMOUSERNAME }}/.ssh"
    EXTERNAL_HOST_KEY_OWNER: root
    EXTERNAL_HOST_KEY_GROUP: root
    EXTERNAL_HOST: "shell"
    USERNAME: "{{ ATMOUSERNAME }}"
  roles:
    - sshkey-host-access

- name: this is the play for adding an ssh key to a guacamole user
  hosts: atmosphere
  vars:
    EXTERNAL_HOST_KEY_DIR: "/etc/guacamole/keys/{{ ATMOUSERNAME }}"
    EXTERNAL_HOST_KEY_OWNER: tomcat7
    EXTERNAL_HOST_KEY_GROUP: tomcat7
    EXTERNAL_HOST_KEY_NAME: "_guac"
    EXTERNAL_HOST: "guac_server"
    USERNAME: "{{ ATMOUSERNAME }}"
  roles:
    - { role: "sshkey-host-access", when: SETUP_GUACAMOLE == true }
