---

# This block executes on the target host
- block:
    - name: ensure the existence of the user directory
      file:
        path: "{{ KEY_LOCAL_DIR }}"
        owner: "{{ KEY_LOC_OWNER }}"
        group: "{{ KEY_LOC_GROUP }}"
        mode: 0700
        state: directory

    - name: check the existence of a given ssh key by name
      stat:
        path: "{{ FULL_PRIVKEY_PATH }}"
      register: go_key

    - name: generate the keypair
      command: >
        /usr/bin/ssh-keygen -N '' -t rsa -b 2048 -f {{ KEY_LOCAL_DIR }}/{{ USERNAME }}{{ KEY_LOC_PREFIX }}_default -C {{ USERNAME }}
      when: go_key.stat.exists == False

    - name: set the permissions on the private key file
      file:
        path: "{{ FULL_PRIVKEY_PATH }}"
        mode: 0600
        owner: "{{ KEY_LOC_OWNER }}"
        group: "{{ KEY_LOC_GROUP }}"

    - name: Ensure correct ownership of public key
      file:
        path: "{{ FULL_PUBKEY_PATH }}"
        owner: "{{ KEY_LOC_OWNER }}"
        group: "{{ KEY_LOC_GROUP }}"

    - name: add the key name to .default_ids
      lineinfile:
        dest: "{{ KEY_LOCAL_DIR }}/.default_ids"
        line: "{{ USERNAME }}{{ KEY_LOC_PREFIX }}_default"
        create: yes
        state: present
        owner: "{{ KEY_LOC_OWNER }}"
        group: "{{ KEY_LOC_GROUP }}"

    - name: transfer the public key from {{ EXTERNAL_HOST }} host to controller
      fetch:
        src: "{{ FULL_PUBKEY_PATH }}"
        dest: "{{ LOCAL_PUBKEY_DIR }}"
        flat: yes
  delegate_to: "{{ EXTERNAL_HOST }}"

- name: add authorized access to vm from the {{ EXTERNAL_HOST }} host
  authorized_key:
    key: "{{ lookup('file', LOCAL_FULL_PUBKEY_PATH) }}"
    state: present
    user: "{{ USERNAME }}"
  tags:
    - ssh-keys
    - debug

- name: remove user key from controller node
  local_action:
    module: file
    path: "{{ LOCAL_FULL_PUBKEY_PATH }}"
    state: absent
  tags:
    - ssh-keys
    - delete-key
